### ISSUE TITLE
Can't run LEMS_NoisyCurrentInput.xml

### ISSUE THREAD

**Issue by rgerkin** [OpenSourceBrain/StochasticityShowcase#1]
@pgleeson @justasb

I'm running this through pyNeuroML (which I don't think is the problem):  
```
from pyneuroml import pynml
pynml.run_lems_with_jneuroml('LEMS_NoisyCurrentInput.xml')
```

which tells me that things failed with (abbreviated):  
```
pyNeuroML >>> *** Command: java -Xmx400M  -jar  ".../site-packages/pyNeuroML-0.2.0-py3.4.egg/pyneuroml/lib/jNeuroML-0.8.0-jar-with-dependencies.jar"  "LEMS_NoisyCurrentInput.xml"  ***
```

So I run that on the command line to get the specific error:  
```
$ java -Xmx400M  -jar  ".../site-packages/pyNeuroML-0.2.0-py3.4.egg/pyneuroml/lib/jNeuroML-0.8.0-jar-with-dependencies.jar"  "LEMS_NoisyCurrentInput.xml"
 jNeuroML v0.8.0
Loading: /.../StochasticityShowcase/NeuroML2/LEMS_NoisyCurrentInput.xml with jLEMS...
org.lemsml.jlems.core.run.RuntimeError: Error at PathDerivedVariable eval(): tgt: null; sin: IF_curr_exp[IF_curr_exp]; tgtvar: I; path: synapses[*]/I
	at org.lemsml.jlems.core.run.PathDerivedVariable.eval(PathDerivedVariable.java:128)
	at org.lemsml.jlems.core.run.StateType.initialize(StateType.java:373)
	at org.lemsml.jlems.core.run.StateInstance.initialize(StateInstance.java:177)
	at org.lemsml.jlems.core.run.StateInstance.initialize(StateInstance.java:160)
	at org.lemsml.jlems.core.run.MultiInstance.initialize(MultiInstance.java:63)
	at org.lemsml.jlems.core.run.StateInstance.initialize(StateInstance.java:165)
	at org.lemsml.jlems.core.run.MultiInstance.initialize(MultiInstance.java:63)
	at org.lemsml.jlems.core.run.StateInstance.initialize(StateInstance.java:165)
	at org.lemsml.jlems.core.sim.Sim.run(Sim.java:276)
	at org.lemsml.jlems.core.sim.Sim.run(Sim.java:152)
	at org.lemsml.jlems.core.sim.Sim.run(Sim.java:143)
	at org.neuroml.export.utils.Utils.loadLemsFile(Utils.java:391)
	at org.neuroml.export.utils.Utils.runLemsFile(Utils.java:364)
	at org.neuroml.JNeuroML.main(JNeuroML.java:306)
Caused by: org.lemsml.jlems.core.run.RuntimeError: 
Problem while trying to return a value for variable I: NaN
```

and then a bunch of INFO messages.  Do you know what I am missing to be able to run this example successfully?

**Comment by pgleeson** [comment]
@rgerkin That looks like an old version of pyNeuroML... I'd pull the latest from github (or merge from master), install it and try again.

**Comment by pgleeson** [comment]
I assume it's ok to close this now @rgerkin?

**Comment by rgerkin** [comment]
Yes.
