### ISSUE TITLE
Enable recording of spiketrains from poissonFiringSynapses etc. in Neuron

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/StochasticityShowcase#6]
Works in LEMS, not Neuron yet...

**Comment by sanjayankur31** [comment]
Still an issue:

```
pynml LEMS_OUCurrentInput_test.xml -neuron -nogui -run

pyNeuroML >>> ERROR - execute_command_in_dir returned with output:  jNeuroML v0.12.2
(INFO) Reading from: /home/asinha/Documents/02_Code/00_mine/models/StochasticityShowcase/NeuroML2/LEMS_OUCurrentInput_test.xml
(WARNING) No internal variable is linked to the exposure: tsince for ComponentType ouCurrentSource at: org.lemsml.jlems.core.type.dynamics.Dynamics.realResolve(Dynamics.java:272)
(INFO) Creating NeuronWriter to output files to /home/asinha/Documents/02_Code/00_mine/models/StochasticityShowcase/NeuroML2
(INFO) Adding simulation Component(id=simnet1 type=Simulation) of network/component: net1 (Type: network)
(INFO) Adding population: Pop0
(INFO) -- Writing to mod: /home/asinha/Documents/02_Code/00_mine/models/StochasticityShowcase/NeuroML2/IF_curr_exp.mod
(INFO) File /home/asinha/Documents/02_Code/00_mine/models/StochasticityShowcase/NeuroML2/IF_curr_exp.mod exists and is identical
(INFO) Adding projections/connections...
(INFO) -- Writing to mod: /home/asinha/Documents/02_Code/00_mine/models/StochasticityShowcase/NeuroML2/pulseGen0.mod
(INFO) File /home/asinha/Documents/02_Code/00_mine/models/StochasticityShowcase/NeuroML2/pulseGen0.mod exists and is identical
(INFO) -- Writing to mod: /home/asinha/Documents/02_Code/00_mine/models/StochasticityShowcase/NeuroML2/noisyCurrentSource1.mod
(INFO) File /home/asinha/Documents/02_Code/00_mine/models/StochasticityShowcase/NeuroML2/noisyCurrentSource1.mod exists and is identical
(INFO) -- Writing to mod: /home/asinha/Documents/02_Code/00_mine/models/StochasticityShowcase/NeuroML2/noisyCurrentSource2.mod
(INFO) File /home/asinha/Documents/02_Code/00_mine/models/StochasticityShowcase/NeuroML2/noisyCurrentSource2.mod exists and is identical
(INFO) -- Writing to mod: /home/asinha/Documents/02_Code/00_mine/models/StochasticityShowcase/NeuroML2/noisyCurrentSource3.mod
(INFO) File /home/asinha/Documents/02_Code/00_mine/models/StochasticityShowcase/NeuroML2/noisyCurrentSource3.mod exists and is identical
(INFO) Setting up recorders...
org.neuroml.export.exceptions.GenerationException: Error with LEMS content
        at org.neuroml.export.neuron.NeuronWriter.getMainScript(NeuronWriter.java:1779)
        at org.neuroml.export.neuron.NeuronWriter.generateMainScriptAndMods(NeuronWriter.java:289)
        at org.neuroml.export.neuron.NeuronWriter.generateAndRun(NeuronWriter.java:157)
        at org.neuroml.JNeuroML.main(JNeuroML.java:527)
Caused by: org.lemsml.jlems.core.sim.ContentError: Error processing outputfile quantity: Pop0/0/IF_curr_exp/pulseGen0/i
Reference: m_IF_curr_exp_Pop0[0].pulseGen0_i
Original:       Pop0/0/IF_curr_exp/pulseGen0/i
    Type:             VAR_IN_CELL_IN_POP_LIST
    Variable parts:   pulseGen0_i
    Variable:         pulseGen0_i
    Is var in pop:    true (Pop0)
    Is var in syn:    false
    Num in pop:       0
    segmentId:        0
    ** Neuron ref:    m_IF_curr_exp_Pop0[0].pulseGen0_i
    popsOrComponents: [Component(id=Pop0 type=populationList)]
    targetComp:       Component(id=net1 type=network)
    popComp:          Component(id=IF_curr_exp type=IF_curr_exp)
    hocRefsVsInputs:  {Pop0[3]:noisyCurrentSource3=noisy3_0, Pop0[0]:pulseGen0=stimInput_0, Pop0[1]:noisyCurrentSource1=noisy1_0, Pop0[2]:noisyCurrentSource2=noisy2_0}
java.lang.NullPointerException: Cannot invoke "org.lemsml.jlems.core.type.Component.getComponentType()" because "c" is null
        at org.neuroml.export.neuron.NeuronWriter.getMainScript(NeuronWriter.java:1473)
        ... 3 more
```

So paths that work for LEMS don't work for NEURON. That's odd, no? Bug or something that needs documentation perhaps?

PS: this is with some tweaks I made to get better information about where the errors happen so uses at least know what quantity path they should be tweaking. Opening a PR In org.neuroml.export in a bit.
